#  Python build by Erik Bautista

image: python:3.8

definitions:
  caches:
    mongo: /usr/bin/
  services:
    mongo:
      image: mongo
  steps:
    - step: &build-and-unittest
        max-time: 1
        caches:
          - mongo
          - pip
        name: Build and Run Test
        script:
          - if ! which mongo >/dev/null; then wget https://repo.mongodb.org/apt/debian/dists/buster/mongodb-org/4.4/main/binary-amd64/mongodb-org-shell_4.4.5_amd64.deb; apt install ./mongodb-org-shell_4.4.5_amd64.deb; fi
          - mongo --port 27017 --eval 'db.getSiblingDB("team22_demand").createUser({ user:"developer", pwd:"'"$MONGO_TEAM_PW"'", roles:["readWrite"]})'
          - cd ../
          - git clone git@bitbucket.org:swe-spring-2021-team-22/team22-common-services-backend.git
          - cd team22-common-services-backend/
          - if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
          - cd ../build
          - if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
          - cd unittest
          - python3 -m xmlrunner discover -p "*test*.py" -o ./test-reports/  
        services: 
          - mongo

pipelines:
  default:
    - step: *build-and-unittest
  
  branches:
    master:
      - step: *build-and-unittest

      - step:
          name: Deploy to Demand Cloud Production
          deployment: production
          clone:
             enabled: false
          script:
            - ssh -A -tt -i /opt/atlassian/pipelines/agent/ssh/id_rsa -o 'StrictHostKeyChecking=no' -p ${PORT:-22} $USER@$DEMAND_SERVER "bash -c '/home/team22/webhooks/team22-redeploy.sh ${BITBUCKET_REPO_SLUG} ${BITBUCKET_COMMIT}'"
